### ISSUE TITLE
Show song name from metadata?

### ISSUE THREAD

**Issue by MosheBerman** [mattgallagher/AudioStreamer#20]
I have sent several hours trying to get the song name to display. I've followed the instructions in the original post on Matts website, or at least I've tried.

Can someone from the community help me with that?

**Comment by sebsto** [comment]
just try my repository I included a bunch of fixes for this http://github.com/sebsto/AudioStreamer

**Comment by MosheBerman** [comment]
Neat!

**Comment by ototoapp** [comment]
I can't find page  http://github.com/sebsto/AudioStreamer 
i also try to show the name .

can you help ? 

please ...
