### ISSUE TITLE
Seek in song problem

### ISSUE THREAD

**Issue by Yosifz8** [mattgallagher/AudioStreamer#48]
Hi

i used AudioStremer project and tried to seek in mp3 song that i stream, and i have a problem that everytime the song start from the begin instead from where i want to seek, and it give me a Log MSG :

"AudioQueue changed state in unexpected way."

I tried to stream songs from couple of servers.

**Comment by cytryn** [comment]
I also have this problem... any progress?

**Comment by Yosifz8** [comment]
I now use avplayer class of iPhone, it work very good and the seeking good too.
