### ISSUE TITLE
Is there way to play local MP3 files?

### ISSUE THREAD

**Issue by emile818** [mattgallagher/AudioStreamer#54]
@mattgallagher any idea how i can make CFHTTPMessageCreateRequest work with local files.

PS:  I want to init the streamer on  something like this: file://localhost/var/mobile/Applications/59CF743B-6927-431C-9461-D3930DB31F38/Documents/text.mp3

**Comment by azone** [comment]
You can use AVAudioPlayer to play local audio.

**Comment by emile818** [comment]
@azone done, such a cool framework the AVAudioPlayer. Thanks.
