### ISSUE TITLE
Not supporting with iOS 7

### ISSUE THREAD

**Issue by enadun** [mattgallagher/AudioStreamer#76]
This project is not working on iOS 7. In some times, we stop playing and play again, it is continuously buffering and not start playing again. Did anyone else get the same issue ?

**Comment by bennyk** [comment]
Hi Nadun,

I have been using AudioStreamer on iOS7 but don't see the error you were describing. Is there a streaming URL to check this out?

On Friday, October 11, 2013 7:08 PM, Nadun De Silva notifications@github.com wrote:

This project is not working on iOS 7. In some times, we are stop playing and playing again, it is continuously buffering and not start playing again. Did anyone else get the same issue ?

**Comment by enadun** [comment]
Hi bennyk,

Here is the URL, what I'm using. http://live.tnlrn.com:8002
This is perfectly working on iOS 6. When I try this on upgraded iPhone, I have face the following issue.
It's working on the first time. Then I stop the player and play the player again. It shows me the buffering button for a long time and doesn't start to play again.
I don't have an iOS 7 simulator and still I'm using xCode 4.6. I just check this by using an upgraded iPhone.
Did you check this on a simulator or a real device. What is your xCode version. May it be an xCode issue ?

Thank You !

**Comment by bennyk** [comment]
Hi Nadun,

I am using Xcode 5. I tested AudioStreamer on ipad3 and iphone4. Do you get similar behavior using other streaming URL too?

I tried your streaming URL, my AudioStreamer keeps spinning endlessly. Could it be a server side issue coz I can get stable stream from other source?

**Comment by enadun** [comment]
Hi bennyk,

I also thought that would be a server issue. But it's working perfectly on iOS 6 devices.

I didn't try with default URL's. I'll try and let you know. Could you please check this URL with iOS 6 device whether it's gain you the same issu or not ?

**Comment by bennyk** [comment]
Hi Nadun,

I tested your streaming URL on VLC desktop. It works!

I run AudioStreamer on Xcode Simulator  it is spinning endlessly too. I am turning my suspicious on changes in Apple codec layer while transitioning from iOS6 to iOS7.

PS: I don't have any more device in iOS6.

On Saturday, October 12, 2013 1:06 AM, Nadun De Silva notifications@github.com wrote:

Hi bennyk,
I also thought that would be a server issue. But it's working perfectly on iOS 6 devices.
I didn't try with default URL's. I'll try and let you know. Could you please check this URL with iOS 6 device whether it's gain you the same issu or not ?
