### ISSUE TITLE
Failing to start ShoutCast Stream

### ISSUE THREAD

**Issue by jeremyquinn** [mattgallagher/AudioStreamer#80]
I have had an old hacked up version of AudioStreamer in an App for years.
Either the switch to iOS7 or a new ShoutCast provider for the Station, has started causing occasional problems starting the stream.

I checked out the latest version and found it was unable to start the stream at all :
http://galaxynorth.simplecast.co.uk:9414

I sometimes saw this : Audio packets are larger than kAQDefaultBufSize
Doubling it's size did not help.

It's state is AS_WAITING_FOR_DATA

Thanks for any suggestions

**Comment by saturngod** [comment]
@jeremyquinn  , did you solve it ?
