### ISSUE TITLE
Soundcloud certain songs not working

### ISSUE THREAD

**Issue by clicklabs** [mattgallagher/AudioStreamer#84]
https://api.soundcloud.com/tracks/75136216/stream?client_id=b45b1aa10f1ac2941910a7f0d10f8e28

This song streams well in the desktop browser, mobile safari but not with the AudioStreamer.

Update: This got resolved. Somehow the automatic direction works, previously we were handling on our own.

**Comment by arjunbanker** [comment]
We

**Comment by flowdeskadmin** [comment]
Hello, @clicklabs 
I'm also facing same issue,
Can you please tell me how to fix it?
